#!/usr/bin/env bash
# Transfers a file from our client to a server

# Check if all required arguments are provided
if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign arguments to variables
PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Check if the file exists
if [ ! -f "$PATH_TO_FILE" ]; then
    echo "File not found: $PATH_TO_FILE"
    exit 1
fi

# File transfer using scp
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$PATH_TO_FILE" "${USERNAME}@${IP}:~/"
