#!/bin/bash

# Check if an argument is passed
if [ -z "$1" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Ping the IP address 5 times
for i in $(seq 1 5); do
    ping -c 1 "$1"
done
