#!/usr/bin/env bash
# configures a server to listening on port 80 of all servers active IPv4 IPs

nginx to run and listening on port 80
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
