#!/usr/bin/env bash

# Display the PID and process name of processes whose name contain the word 'bash'
# Do not use the 'ps' command
for pid in $(pgrep -x bash); do
  echo "$pid $(readlink /proc/$pid/exe | xargs -0 basename)"
done

