#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

# Use a for loop to iterate over a sequence of numbers from 1 to 10
for i in {1..10}; do
  # Print "Best School" to the console
  echo "Best School"
done

# End of script
