#!/usr/bin/env bash
# This script displays numbers from 1 to 20, with custom messages for the 4th, 9th, and 17th iterations

i=1
while [ $i -le 20 ]; do
  case $i in
    4)
      echo "4"
      echo "bad luck from China"
      ;;
    9)
      echo "9"
      echo "bad luck from Japan"
      ;;
    17)
      echo "17"
      echo "bad luck from Italy"
      ;;
    *)
      echo "$i"
      ;;
  esac
  i=$((i + 1))
done

