#!/usr/bin/env bash

# This script connects to a server using SSH with a private key

# Connect to the server using SSH with the specified private key and username
ssh -i ~/.ssh/school ubuntu@server01
